# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/pavel/.local/share/ue/Linux_Unreal_Engine_5.4.4
GAMEPROJECTFILE =/home/pavel/projects/ue/ue5-city-building/ZMR.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	ZMR-Linux-DebugGame  \
	ZMR-Linux-Shipping  \
	ZMR \
	ZMREditor-Linux-DebugGame  \
	ZMREditor-Linux-Shipping  \
	ZMREditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend ZMREditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug ZMREditor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

ZMR-Linux-DebugGame:
	 $(PROJECTBUILD) ZMR Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ZMR-Linux-Shipping:
	 $(PROJECTBUILD) ZMR Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ZMR:
	 $(PROJECTBUILD) ZMR Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

ZMREditor-Linux-DebugGame:
	 $(PROJECTBUILD) ZMREditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ZMREditor-Linux-Shipping:
	 $(PROJECTBUILD) ZMREditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ZMREditor:
	 $(PROJECTBUILD) ZMREditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
